language: java
jdk: openjdk8
sudo: false
#script: mvn clean org.jacoco:jacoco-maven-plugin:0.8.5:prepare-agent install org.jacoco:jacoco-maven-plugin:0.8.5:report
#script: mvn clean
script : mvn evosuite:generate evosuite:export -Duse_separate_classloader=false jacoco:prepare-agent install
#script: mvn clean evosuite:generate evosuite:export org.apache.maven.plugins:maven-surefire-plugin:2.17:test
#script:mvn clean evosuite:generate evosuite:export org.apache.maven.plugins:maven-surefire-plugin:2.17:test jacoco:prepare-agent install jacoco:report
after_success:
#  - bash <(curl -s https://codecov.io/bash) org.apache.maven.plugins:maven-surefire-plugin:2.17:test
#   - mvn clean evosuite:generate evosuite:export org.apache.maven.plugins:maven-surefire-plugin:2.17:test jacoco:prepare-agent install jacoco:report
#   - mvn jacoco:prepare-agent install jacoco:report
   - bash <(curl -s https://codecov.io/bash)
after_deploy:
   - mvn jacoco:report
   - bash <(curl -s https://codecov.io/bash)