language: java
sudo: false
script: mvn clean org.jacoco:jacoco-maven-plugin:0.8.5:prepare-agent install org.jacoco:jacoco-maven-plugin:0.8.5:report
#script: mvn clean evosuite:generate evosuite:export test jacoco:prepare-agent install jacoco:report
after_success:
  - bash <(curl -s https://codecov.io/bash)